// <auto-generated />
using MessageBoardApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageBoardApi.Migrations
{
    [DbContext(typeof(MessageBoardApiContext))]
    [Migration("20240104175524_UpdateDatePropertyTypeInModelAndSeedNewData")]
    partial class UpdateDatePropertyTypeInModelAndSeedNewData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoardApi.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .HasColumnType("longtext");

                    b.Property<string>("UserMessage")
                        .HasColumnType("longtext");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Author = "newbieDrummer99",
                            Date = "2024-01-04",
                            Group = "Music Makers",
                            UserMessage = "Best drum kit for a beginner?"
                        },
                        new
                        {
                            MessageId = 2,
                            Author = "gamerchick",
                            Date = "2020-05-30",
                            Group = "PC Gamers",
                            UserMessage = "Favorite loadout for Overwatch?"
                        },
                        new
                        {
                            MessageId = 3,
                            Author = "nightryder82",
                            Date = "2022-03-25",
                            Group = "Cycling Enthusiasts",
                            UserMessage = "Looking for rain-resistant tires for my bike"
                        },
                        new
                        {
                            MessageId = 4,
                            Author = "muddyB00tz",
                            Date = "2019-12-23",
                            Group = "Hiking fanatics",
                            UserMessage = "Best hiking trails in Cascade mountain range?"
                        },
                        new
                        {
                            MessageId = 5,
                            Author = "StampNerd",
                            Date = "2007-11-03",
                            Group = "Stamp collectors",
                            UserMessage = "Can someone tell me the year of this stamp?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
